pipeline {
    agent any
    environment {
        
        ecr_reg_address = "421320058418.dkr.ecr.us-west-2.amazonaws.com"
        repo = "ankur-robot-shop"
        
    }

    stages {
        stage('Git Clone') {
            steps {
                git 'https://github.com/ankur-kesari/robot-shop.git'
                }
        }
        
        stage('Docker Build and Tagging'){
            steps{
          
                sh  'docker build -t cart/robot-shop cart/'
                sh 'docker tag cart/robot-shop ${reg_address}/${repo}:cart-build'
                 }
        }
        stage('ECR Authentication'){
                steps{
                 sh 'aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 421320058418.dkr.ecr.us-west-2.amazonaws.com'
                  }
        }
        
        stage('Docker Push'){
                 steps{
                     sh 'docker push ${reg_address}/${repo}:cart-build'
            
                    }
        }
    }
}
