pipeline {
    agent any
    environment {
        
        ecr_reg_address = "421320058418.dkr.ecr.us-west-2.amazonaws.com"
        repo = "ankur-robot-shop"
        
    }

    stages {
        stage('Git Clone') {
            steps {
                git 'https://github.com/ankur-kesari/robot-shop.git'
                }
        }
        
        stage('Docker Build'){
            steps{
          
                sh  'docker build -t web/robot-shop web/'          
                sh 'docker tag web/robot-shop ${ecr_reg_address}/${repo}:web-build'      
                 }
        }
        stage('ECR Authentication'){
                steps{
                 sh 'sudo aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 421320058418.dkr.ecr.us-west-2.amazonaws.com'
                  }
        }
        
        stage('Docker Push'){
                 steps{
                     sh 'docker push ${ecr_reg_address}/${repo}:web-build'    
            
                    }
        }
    }
}
